0
1
raised ValueError()
ret was: None
raised ValueError('generator already executing',)
raised TypeError("can't pend throw to just-started generator",)
0
ignore CancelledError
1
TypeError
None
CancelledError()
CancelledError()
1
